name: Bug Report
description: Submit bug reports to help improve
title: "[Bug] "
labels:
  - Bug
body:
  - type: checkboxes
    attributes:
      label: Check the following items
      options:
        - label: I have looked up relevant Issue
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: Please describe in detail the problems encountered. If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package Version
      description: Enter the version you are using
      placeholder: E.g. 6.0.0-beta6
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Platform or environment where the bug occurs
      placeholder: E.g. Windows 11 22631
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: Describe in detail the reproduction
      placeholder: If unable to reproduce, enter "unable to reproduce"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here
    validations:
      required: false